# Generated by Django 4.1 on 2023-06-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "name",
                    models.CharField(
                        default="", max_length=60, primary_key=True, serialize=False
                    ),
                ),
                ("gstin", models.CharField(default="", max_length=30)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=9
                    ),
                ),
                ("address", models.CharField(default="", max_length=70)),
                ("slug", models.SlugField(default="default_dealer")),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("packet", models.IntegerField(default=0)),
                ("slug", models.SlugField(blank=True, default="item")),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "invoice_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, null=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=9)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.dealer",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recieving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "type",
                    models.CharField(
                        choices=[("BORROW", "Borrow"), ("PAID", "Paid")], max_length=6
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.dealer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoiceId", models.CharField(default="", max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="stock.dealer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lend_amt", models.IntegerField(default=0)),
                ("rcv_amt", models.IntegerField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "name",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.dealer",
                    ),
                ),
            ],
        ),
    ]
